name: votacoes
channels:
  - nvidia
  - pytorch
  - huggingface
  - conda-forge
  - anaconda
  
dependencies:
  - python=3.11
  - fa2
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - requests
  - networkx
  - transformers
  - huggingface_hub
  - accelerate
  - deepspeed
  - tabulate
  - pip
  - pip: 
    - ipysigma
    - torch@https://download.pytorch.org/whl/cu118/torch-2.3.1%2Bcu118-cp311-cp311-linux_x86_64.whl
    - torchvision@https://download.pytorch.org/whl/cu118/torchvision-0.18.1%2Bcu118-cp311-cp311-linux_x86_64.whl
    - torchaudio@https://download.pytorch.org/whl/cu118/torchaudio-2.3.1%2Bcu118-cp311-cp311-linux_x86_64.whl